import React, { useState, useEffect, useRef } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    SafeAreaView,
    StatusBar,
    ScrollView,
    Alert,
    ActivityIndicator,
    Dimensions,
    Animated
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { LinearGradient } from 'expo-linear-gradient';
import { useGlobalTheme } from './themeStore';
import { generateGeminiRiddles, getRandomFallbackRiddles } from '../src/assets/API/gemini';

const { width, height } = Dimensions.get('window');
const CONFETTI_COLORS = ['#FFD700', '#FF4081', '#00E676', '#29B6F6', '#AB47BC', '#FF9100', '#7C4DFF', '#FF1744', '#00E5FF'];

// --- CONFETTI PARTICLE COMPONENT ---
const ConfettiParticle = ({ index }) => {
    const animY = useRef(new Animated.Value(-30)).current;
    const animX = useRef(new Animated.Value(0)).current;
    const animRotate = useRef(new Animated.Value(0)).current;
    const animOpacity = useRef(new Animated.Value(1)).current;

    const color = CONFETTI_COLORS[index % CONFETTI_COLORS.length];
    const size = Math.floor(Math.random() * 8) + 8;
    const startX = Math.random() * (width - 40);
    const targetX = startX + (Math.random() * 160 - 80);

    useEffect(() => {
        Animated.parallel([
            Animated.timing(animY, {
                toValue: height * 0.75 + Math.random() * 100,
                duration: 1600 + Math.random() * 800,
                useNativeDriver: true,
            }),
            Animated.timing(animX, {
                toValue: targetX - startX,
                duration: 1600 + Math.random() * 800,
                useNativeDriver: true,
            }),
            Animated.timing(animRotate, {
                toValue: 1,
                duration: 1400 + Math.random() * 800,
                useNativeDriver: true,
            }),
            Animated.timing(animOpacity, {
                toValue: 0,
                duration: 2000 + Math.random() * 500,
                useNativeDriver: true,
            }),
        ]).start();
    }, []);

    const spin = animRotate.interpolate({
        inputRange: [0, 1],
        outputRange: ['0deg', `${index % 2 === 0 ? 720 : -720}deg`],
    });

    return (
        <Animated.View
            style={{
                position: 'absolute',
                left: startX,
                top: 0,
                width: index % 2 === 0 ? size : size * 1.4,
                height: size,
                borderRadius: index % 3 === 0 ? size / 2 : 2,
                backgroundColor: color,
                transform: [
                    { translateY: animY },
                    { translateX: animX },
                    { rotate: spin },
                ],
                opacity: animOpacity,
                zIndex: 999,
            }}
        />
    );
};

const ConfettiContainer = ({ active, keyId }) => {
    if (!active) return null;
    return (
        <View style={StyleSheet.absoluteFillObject} pointerEvents="none">
            {Array.from({ length: 45 }).map((_, i) => (
                <ConfettiParticle key={`${keyId}-${i}`} index={i} />
            ))}
        </View>
    );
};

export default function RiddlesScreen() {
    const router = useRouter();
    const [isDark] = useGlobalTheme();
    const params = useLocalSearchParams();
    const category = params?.category || params?.courseTitle || "General Knowledge";

    // --- STATES ---
    const [questions, setQuestions] = useState(() => getRandomFallbackRiddles());
    const [loading, setLoading] = useState(false);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [selectedOption, setSelectedOption] = useState(null);
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [score, setScore] = useState(0);
    const [isFinished, setIsFinished] = useState(false);
    const [showConfetti, setShowConfetti] = useState(false);
    const [confettiKey, setConfettiKey] = useState(0);

    // Fetch unique Riddles generated by Gemini Key for each attempt
    const loadRiddles = async () => {
        setIsFinished(false);
        setCurrentIndex(0);
        setSelectedOption(null);
        setIsSubmitted(false);
        setScore(0);
        setShowConfetti(false);

        try {
            const generated = await generateGeminiRiddles(category);
            if (generated && generated.length > 0) {
                setQuestions(generated);
            }
        } catch (error) {
            console.error("Failed to load riddles:", error);
            setQuestions(getRandomFallbackRiddles());
        }
    };

    useEffect(() => {
        loadRiddles();
    }, [category]);

    const currentQ = questions[currentIndex];
    const progressPercentage = questions.length > 0 ? ((currentIndex + 1) / questions.length) * 100 : 0;

    const triggerConfetti = () => {
        setConfettiKey(prev => prev + 1);
        setShowConfetti(true);
        setTimeout(() => {
            setShowConfetti(false);
        }, 2200);
    };

    const handleGoBack = () => {
        const dest = params?.parentRoute || params?.targetRoute;
        if (dest && dest !== '/coursedetails') {
            router.replace(dest);
            return;
        }

        if (params?.lessonTitle && params?.courseTitle) {
            router.replace({
                pathname: '/lessondetails',
                params: {
                    courseTitle: params.courseTitle,
                    lessonTitle: params.lessonTitle,
                    description: params.description || '',
                    url: params.url || '',
                    mcqs: params.mcqs || '',
                    parentRoute: dest || '/coursedetails'
                }
            });
            return;
        }

        if (dest) {
            router.replace(dest);
            return;
        }

        router.replace('/coursedetails');
    };

    // --- HANDLERS ---
    const handleSelectOption = (letter) => {
        if (!isSubmitted) {
            setSelectedOption(letter);
        }
    };

    const handleActionBtn = () => {
        if (!selectedOption) {
            Alert.alert("Hold on!", "Please select an answer before submitting.");
            return;
        }

        if (!isSubmitted) {
            // Check if correct
            const isCorrect = selectedOption === currentQ?.answer;
            if (isCorrect) {
                setScore(prev => prev + 1);
                triggerConfetti();
            }
            setIsSubmitted(true);
        } else {
            // Next Riddle Logic
            if (currentIndex < questions.length - 1) {
                setCurrentIndex(currentIndex + 1);
                setSelectedOption(null);
                setIsSubmitted(false);
            } else {
                // Riddles Finished
                setIsFinished(true);
                triggerConfetti();
            }
        }
    };

        // --- FINISHED STATE ---
    if (isFinished) {
        return (
            <View style={[styles.safeArea, isDark && { backgroundColor: '#121212' }]}>
                <StatusBar barStyle="light-content" backgroundColor="#4C35A5" />
                <ConfettiContainer active={showConfetti} keyId={confettiKey} />

                <View style={styles.headerContainer}>
                    <Text style={styles.courseTitle}>Riddles Completed!</Text>
                </View>

                <View style={[styles.finishedContainer, isDark && { backgroundColor: '#121212' }]}>
                    <View style={[styles.scoreCard, isDark && { backgroundColor: '#1E1E1E', borderColor: '#2A2A2A' }]}>
                        <Text style={styles.trophyIcon}>🏆</Text>
                        <Text style={[styles.scoreTitle, isDark && { color: '#FFFFFF' }]}>Riddle Challenge Results</Text>
                        <Text style={styles.scoreNumber}>{score} / {questions.length}</Text>
                        <Text style={[styles.scoreSubtitle, isDark && { color: '#AAAAAA' }]}>
                            {score === questions.length
                                ? "Outstanding! You solved every single riddle!"
                                : score >= 3
                                    ? "Great job! Your brain is super sharp!"
                                    : "Good effort! Keep practicing to master riddles."}
                        </Text>
                    </View>

                    <TouchableOpacity style={styles.primaryBtn} onPress={handleGoBack}>
                        <Text style={styles.primaryBtnText}>
                            {params?.lessonTitle ? "Continue to Lesson Material" : "Return to Course Module"}
                        </Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    }

       return (
        <View style={[styles.safeArea, isDark && { backgroundColor: '#121212' }]}>
            <StatusBar barStyle="light-content" backgroundColor="#4C35A5" />
            <ConfettiContainer active={showConfetti} keyId={confettiKey} />

            {/* --- CLEAN HEADER SECTION --- */}
            <View style={styles.headerContainer}>
                <Text style={styles.courseTitle}>Riddles</Text>
            </View>

            <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

                {/* --- PROGRESS BAR SECTION --- */}
                <View style={styles.progressHeader}>
                    <Text style={[styles.progressLabel, isDark && { color: '#B39DDB' }]}>Riddles</Text>
                    <Text style={[styles.progressStep, isDark && { color: '#AAAAAA' }]}>Riddle {currentIndex + 1} of {questions.length}</Text>
                </View>
                <View style={[styles.progressTrack, isDark && { backgroundColor: '#2A2A2A' }]}>
                    <LinearGradient
                        colors={['#9B86EE', '#5CA0D3', '#31B998']}
                        locations={[0, 0.6, 1]}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 0 }}
                        style={[styles.progressFill, { width: `${progressPercentage}%` }]}
                    />
                </View>

                {/* --- QUESTION SECTION --- */}
                <Text style={[styles.questionText, isDark && { color: '#FFFFFF' }]}>
                    🧩 {currentIndex + 1}. {currentQ?.question}
                </Text>
                <Text style={[styles.subText, isDark && { color: '#AAAAAA' }]}>Solve the riddle & select the right answer</Text>

                {/* --- OPTIONS SECTION --- */}
                <View style={styles.optionsContainer}>
                    {['A', 'B', 'C', 'D'].map((letter) => {
                        const isSelected = selectedOption === letter;
                        const isCorrectAnswer = currentQ?.answer === letter;

                        let containerStyle = [styles.optionCard, isDark && { backgroundColor: '#1E1E1E', borderColor: '#2A2A2A' }];
                        let badgeStyle = [styles.optionBadge, isDark && { backgroundColor: '#2A2A2A', borderColor: '#333' }];
                        let showCheckmark = false;

                        if (isSubmitted) {
                            if (isCorrectAnswer) {
                                containerStyle = [styles.optionCard, styles.optionCorrectCard, isDark && { backgroundColor: '#1C3829', borderColor: '#00C853' }];
                                showCheckmark = true;
                            } else if (isSelected && !isCorrectAnswer) {
                                containerStyle = [styles.optionCard, styles.optionWrongCard, isDark && { backgroundColor: '#3E1C2B', borderColor: '#F44336' }];
                            }
                        } else if (isSelected) {
                            containerStyle = [styles.optionCard, styles.optionSelectedCard, isDark && { backgroundColor: '#2A2440', borderColor: '#6B52D1' }];
                            badgeStyle = [styles.optionBadge, styles.optionBadgeSelected];
                        }

                        return (
                            <TouchableOpacity
                                key={letter}
                                style={containerStyle}
                                activeOpacity={0.7}
                                onPress={() => handleSelectOption(letter)}
                            >
                                <View style={badgeStyle}>
                                    <Text style={[styles.badgeText, isDark && { color: '#FFF' }, isSelected && !isSubmitted && { color: 'white' }]}>
                                        {letter}
                                    </Text>
                                </View>
                                <Text style={[styles.optionText, isDark && { color: '#FFFFFF' }]}>{currentQ ? currentQ[letter] : ''}</Text>

                                {showCheckmark && (
                                    <Icon name="check-bold" size={24} color="#00C853" style={styles.checkIcon} />
                                )}
                            </TouchableOpacity>
                        );
                    })}
                </View>

            </ScrollView>

            {/* --- ACTION BUTTON --- */}
            <View style={[styles.bottomContainer, isDark && { backgroundColor: '#121212' }]}>
                <TouchableOpacity style={styles.submitBtn} onPress={handleActionBtn}>
                    <Text style={styles.submitBtnText}>
                        {!isSubmitted
                            ? "Submit Answer"
                            : currentIndex === questions.length - 1
                                ? "See Riddle Results"
                                : "Next Riddle"}
                    </Text>
                </TouchableOpacity>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FCFAEE',
    },
    headerContainer: {
        backgroundColor: '#4C35A5',
        borderBottomLeftRadius: 35,
        borderBottomRightRadius: 35,
        paddingTop: 50,
        paddingBottom: 25,
        paddingHorizontal: 25,
        alignItems: 'center',
    },
    courseTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'center',
    },
    scrollContent: {
        padding: 25,
        paddingBottom: 100,
    },
    progressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
        marginTop: 10,
    },
    progressLabel: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#4E33B3',
    },
    progressStep: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#607D8B',
    },
    progressTrack: {
        height: 10,
        backgroundColor: '#E0E0E0',
        borderRadius: 5,
        marginBottom: 40,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        borderRadius: 5,
    },
    questionText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#111',
        textAlign: 'center',
        marginBottom: 10,
        lineHeight: 28,
    },
    subText: {
        fontSize: 15,
        color: '#757575',
        textAlign: 'center',
        marginBottom: 30,
    },
    optionsContainer: {
        gap: 15,
    },
    optionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#D1C4E9',
        borderRadius: 12,
        padding: 12,
        paddingRight: 20,
    },
    optionSelectedCard: {
        borderColor: '#4E33B3',
        borderWidth: 2,
        backgroundColor: '#F3E5F5',
    },
    optionCorrectCard: {
        borderColor: '#00C853',
        borderWidth: 2,
        backgroundColor: '#E8F8EE',
    },
    optionWrongCard: {
        borderColor: '#F44336',
        borderWidth: 2,
        backgroundColor: '#FFEBEE',
    },
    optionBadge: {
        width: 35,
        height: 35,
        backgroundColor: '#F5F5F5',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    optionBadgeSelected: {
        backgroundColor: '#4E33B3',
        borderColor: '#4E33B3',
    },
    badgeText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    optionText: {
        flex: 1,
        fontSize: 15,
        color: '#111',
        fontWeight: '500',
        lineHeight: 22,
    },
    checkIcon: {
        marginLeft: 10,
    },
    bottomContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        backgroundColor: '#FCFAEE',
    },
    submitBtn: {
        backgroundColor: '#4E33B3',
        paddingVertical: 18,
        borderRadius: 30,
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    submitBtnText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    finishedContainer: {
        flex: 1,
        padding: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scoreCard: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 30,
        alignItems: 'center',
        width: '100%',
        marginBottom: 30,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        borderWidth: 1,
        borderColor: '#E0D7F5',
    },
    trophyIcon: {
        fontSize: 50,
        marginBottom: 10,
    },
    scoreTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    scoreNumber: {
        fontSize: 42,
        fontWeight: '900',
        color: '#4E33B3',
        marginBottom: 10,
    },
    scoreSubtitle: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        lineHeight: 20,
    },
    primaryBtn: {
        backgroundColor: '#4E33B3',
        flexDirection: 'row',
        paddingVertical: 16,
        paddingHorizontal: 25,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        marginBottom: 15,
        elevation: 3,
    },
    primaryBtnText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    secondaryBtn: {
        backgroundColor: 'transparent',
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        borderWidth: 1,
        borderColor: '#4E33B3',
    },
    secondaryBtnText: {
        color: '#4E33B3',
        fontSize: 16,
        fontWeight: '600',
    }
});

